# Generated by Django 2.1.5 on 2019-01-15 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article5'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article5',
        ),
    ]
